config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    confirmations: 'confirmations',
    sessions: 'user/sessions'
  }

  resources :wikis
  resources :charges, only: [:new, :create]

  get "welcome/index"
  root to: 'welcome#index'

end

app/views/shared/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWhat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class:'nav-link'%>
              </li>
              <li class="nav-item">
                <%= link_to 'Wikis', wikis_path, class:'nav-link'%>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
            </ul>
            
             <% if user_signed_in? %>
              <div class="nav-item">
                  Signed in as: <strong><%= current_user.email %></strong> |
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                  <% else %>
                  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
                  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
              </div>
            <% end %>
          </div>
      </nav> 

      </body>