config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    confirmations: 'confirmations',
    sessions: 'user/sessions'
  }

  resources :wikis
  resources :charges, only: [:new, :create]

  get "welcome/index"
  root to: 'welcome#index'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :users
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/wikis_controller.rb
class WikisController < ActionController::Base
  #before_action :require_sign_in, except: :show
  #before_action :authorize_user, except: [:new, :create]

  def index
    @wiki = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
    @body = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@wiki.body)
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.create(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Woo hoo! A new Wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "Whoops. There was an error saving your Wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "Whoops. There was an error saving your Wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.delete
      flash[:notice] = "Bye Bye Wiki."
      redirect_to :index
    else
      flash.now[:alert] = "Stubborn little bugger. Please try again."
      render :show
    end
  end

#anything below this is private and can be accessed through Wikis

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body)
  end

  def authorize_user
    wiki = Wiki.find(params[:id])
    unless current_user == wiki.user || current_user.standard?
      flash[:alert] = "You must be a member to do that."
      redirect_to [wiki]
    end
  end
end 

app/views/wikis/_form.html.erb
<div class="container" >

<%= form_for @wiki do |f| %>
      <% if @wiki.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@wiki.errors.count, "error") %></h4>
           <ul>
             <% @wiki.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>

        <div class="form-group">
          <div class="field">
           <%= f.label :title %>
           <%= f.text_field :title, class:"form-control", placeholder: "Whatcha talking about?" %>
          </div>
        </div>

        <div class="form-group">
          <div class="field">
           <%= f.label :body %>
           <%= f.text_area :body, rows: 10, class:'form-control', placeholder: "Talk it up..." %>
          </div>
        </div>

        <% if current_user.role == 'premium' %>
        <div class="form-check">
          <div class="field">
            <%= f.check_box :private %>
            <%= f.label :private %>
          </div>
        </div>
        <% end %>

        <div class="form-group">
         <%= f.submit "Save", class: 'btn-lg btn-primary' %>
        </div>
  <% end %>
</div>

app/views/wikis/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWhat</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <%= render :partial => 'shared/nav' %>
  <body>
    <div class="container">
        <h1>Edit Wiki</h1>
    </div>
    <%= render 'form' %>
</body>

app/views/wikis/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWhat</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <%= render :partial => 'shared/nav' %>
  <body>
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-10">
            <h1>Checkout Wikis</h1>
          </div>
          <div class="col-lg-2">
            <% if user_signed_in? %>
              <%= link_to "Create a new wiki", new_wiki_path, :class => 'btn btn-primary' %>
            <%end%>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <% @wiki.each do |wiki| %>
              <div class="card" style="width: 100%;">
                <div class="card-header">
                  <h4><%= link_to wiki.title, wiki_path(wiki) %></h4>
                </div>
                <div class="card-body">
                  <p class="card-text"><%= markdown(wiki.body).html_safe %></p>
                  <%= link_to "View", wiki_path(wiki), class: 'card-link'%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    </div>
</div>

app/views/wikis/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWhat</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <%= render :partial => 'shared/nav' %>
  <body>
    <div class="container">
        <h1>Create a new Wiki</h1>
        <%= render partial: 'form', locals: {wiki: @wiki} %>
        <% if current_user != 'premium' %>
          <div class="alert alert-info">
            <h3>Psst... Want to keep this a secret?</h3>
            <p>Upgrade to Premium and you can create private Wikis.</p>
            <div class="form-group">
            <%= link_to "Upgrade", new_charge_path, class: 'btn-sm btn-info' %>
            </div>
          </div>
        <% end %>
    </div>
  </body>

app/views/wikis/show.htlm.erb
<div class="container-fluid">
    <h1>  <%= @wiki.title %> </h1>
    <p><%= @wiki.body %></p>
    <hr />
    <div>
      <%= link_to "Edit", edit_wiki_path(@wiki), class:'btn btn-primary' %>
      <%= link_to "Delete", [@wiki], method: :delete, class:'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    </div>
</div>

app/views/wikis/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWhat</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render :partial => 'shared/nav' %>
  <body>
      <div class="container-fluid">
          <h1><%= @wiki.title %> </h1>
          <p><%= markdown(@wiki.body).html_safe %></p>
          <hr />
          <div>
          <% if user_signed_in? %>
            <%= link_to "Edit", edit_wiki_path(@wiki), class:'btn btn-primary' %>
            <% if current_user == @wiki.user %>
              <%= link_to "Delete", wiki_path(@wiki), method: :delete, class:'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
            <%end%>
          <%end%>
          </div>
      </div>
    </body>